// Generated by CoffeeScript 1.7.1
'use strict';
app.controller('RoleCtrl', function($scope, DTOptionsBuilder, DTColumnBuilder) {
  $scope.dtOptions = DTOptionsBuilder.fromSource('/api/customers/roles').withBootstrap();
  $scope.dtColumns = [DTColumnBuilder.newColumn('role').withTitle('角色'), DTColumnBuilder.newColumn('create_time').withTitle('创建时间'), DTColumnBuilder.newColumn('operation').withTitle('操作')];
});

app.controller('PartnerCtrl', function($scope, DTOptionsBuilder, DTColumnBuilder) {
  $scope.dtOptions = DTOptionsBuilder.fromSource('/api/customers/partners').withBootstrap();
  $scope.dtColumns = [DTColumnBuilder.newColumn('role').withTitle('角色'), DTColumnBuilder.newColumn('create_time').withTitle('创建时间'), DTColumnBuilder.newColumn('operation').withTitle('操作')];
});
