// Generated by CoffeeScript 1.7.1
'use strict';
var app;

app = angular.module('emmFrontendApp');

app.controller('MainCtrl', function($scope, $rootScope, $http) {
  $http({
    method: 'GET',
    url: '/api/config'
  }).success(function(data, status, headers, config) {
    console.log(data.menus[0]);
    console.log(data.menus[0].submenus);
    return $rootScope.config = data;
  }).error(function(data, status, headers, config) {
    return alert('/api/config error');
  });
});

app.controller('NavbarCtrl', function($scope, $rootScope, $location, Auth) {
  $scope.user = $rootScope.config.user;
  $scope.company = $rootScope.config.company;
  $scope.logout = function() {
    return Auth.logout().then(function() {
      return $location.path('/login');
    });
  };
});

app.controller('CrumbCtrl', function($scope, $rootScope) {});

app.controller('SidebarCtrl', function($scope, $rootScope) {
  $scope.menus = $rootScope.config.menu;
});
