// Generated by CoffeeScript 1.7.1
'use strict';
var app;

app = angular.module('emmFrontendApp');

app.controller('NavbarCtrl', function($scope, $location, Auth) {
  $scope.menu = [
    {
      title: 'Home',
      link: '/'
    }
  ];
  if (Auth.isLoggedIn()) {
    $scope.menu.push({
      title: 'Settings',
      link: '/settings'
    });
  }
  $scope.logout = function() {
    return Auth.logout().then(function() {
      return $location.path('/login');
    });
  };
  return $scope.isActive = function(route) {
    return route === $location.path();
  };
});
