// Generated by CoffeeScript 1.7.1
'use strict';
exports.roles = function(req, res) {
  var roles;
  roles = [
    {
      role: "管理员",
      create_time: "1987-07-17",
      operation: "123"
    }, {
      role: "管理员",
      create_time: "1987-07-17",
      operation: "123"
    }, {
      role: "管理员",
      create_time: "1987-07-17",
      operation: "123"
    }
  ];
  return res.json(roles);
};

exports.partners = function(req, res) {
  var partners;
  console.log(123);
  partners = [
    {
      role: "管理员",
      create_time: "1987-07-17",
      operation: "123"
    }, {
      role: "管理员",
      create_time: "1987-07-17",
      operation: "123"
    }, {
      role: "管理员",
      create_time: "1987-07-17",
      operation: "123"
    }
  ];
  return res.json(partners);
};
