// Generated by CoffeeScript 1.7.1
'use strict';
var customers;

customers = require('../controllers/api/customers');

module.exports = function(app) {
  app.route('/api/customers/roles').get(customers.roles);
  return app.route('/api/customers/partners').get(customers.partners);
};
